CREATE TABLE PESSOA(
	
		CPF VARCHAR(11) PRIMARY KEY,
		USERNAME VARCHAR(40) UNIQUE,
		NOME VARCHAR(130) NOT NULL,
		TELEFONE VARCHAR(11)

);


CREATE TABLE ALUNO(
		
		CPF VARCHAR(11) PRIMARY KEY,
		GRADUACAO VARCHAR(30),
		ARTE VARCHAR(30),
		IDADE INT,
		SEXO VARCHAR(1),
		CONSTRAINT FK_CPF FOREIGN KEY(CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE

);

CREATE TABLE PROFESSOR(
		
		CPF VARCHAR(11) PRIMARY KEY,
		GRADUACAO VARCHAR(30),
		ARTE VARCHAR(30),
		CONSTRAINT FK_CPF FOREIGN KEY(CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE
	
);

CREATE TABLE IMOVEL(

		ID SERIAL PRIMARY KEY,
		RUA VARCHAR(200),
		NUMERO INT,
		CEP VARCHAR(8),
		ESTADO VARCHAR(30),
		CIDADE VARCHAR(100),
		TAMANHO FLOAT,
		ABERTURA VARCHAR(1),
		JA_UTILIZADO VARCHAR(1),
		LOCADOR VARCHAR(11),
		CONSTRAINT CK_ABERTURA CHECK(UPPER(ABERTURA) IN('S', 'N')),
		CONSTRAINT CK_UTILIZADO CHECK(UPPER(JA_UTILIZADO) IN('S', 'N')),
		CONSTRAINT FK_LOCADOR FOREIGN KEY(LOCADOR) REFERENCES PESSOA(CPF) ON DELETE CASCADE
);


CREATE TABLE TIPO(

		CPF VARCHAR(11),
		TIPO VARCHAR(10),
		CONSTRAINT PK_TIPO PRIMARY KEY(CPF, TIPO),
		CONSTRAINT FK_CPF FOREIGN KEY(CPF) REFERENCES PESSOA(CPF) ON DELETE CASCADE
	
);

CREATE TABLE PAGAMENTO(
		
		N_BOLETO SERIAL PRIMARY KEY,
		METODO VARCHAR(10),
		VALOR FLOAT
	
);

CREATE TABLE COBRANCA(

		PROFESSOR VARCHAR(11) NOT NULL,
		ALUNO VARCHAR(11) NOT NULL,
		PAGAMENTO INT NOT NULL,
		CONSTRAINT FK_PAGAMENTO FOREIGN KEY(PAGAMENTO) REFERENCES PAGAMENTO(N_BOLETO),
		CONSTRAINT FK_PROFESSOR FOREIGN KEY(PROFESSOR) REFERENCES PROFESSOR(CPF),
		CONSTRAINT FK_ALUNO FOREIGN KEY(ALUNO) REFERENCES ALUNO(CPF)
	
);

CREATE TABLE FORNECEDOR(
		
		CNPJ VARCHAR(14) PRIMARY KEY,
		NOME VARCHAR(130) NOT NULL,
		USERNAME VARCHAR(40) UNIQUE,
		TELEFONE1 VARCHAR(11),
		TELEFONE2 VARCHAR(11),
		RUA VARCHAR(200),
		NUMERO INT,
		CEP VARCHAR(8),
		ESTADO VARCHAR(30),
		CIDADE VARCHAR(100),
		CONSTRAINT UN_ENDERECO UNIQUE(RUA, NUMERO, CEP, ESTADO, CIDADE)

);

CREATE TABLE PRODUTO(
		
		CODIGO SERIAL PRIMARY KEY,
		FORNECEDOR VARCHAR(14) NOT NULL,
		CATEGORIA VARCHAR(15),
		CUSTO FLOAT,
		ESTADO VARCHAR(20),
		MARCA VARCHAR(50),
		TAMANHO VARCHAR(1),
		TIPO VARCHAR(11),
		CONSTRAINT FK_PRODUTO FOREIGN KEY(FORNECEDOR) REFERENCES FORNECEDOR(CNPJ)
);


CREATE TABLE COMPRA(
	
		PROFESSOR VARCHAR(11),
		PRODUTO INT,
		CONSTRAINT PK_COMPRA PRIMARY KEY(PROFESSOR, PRODUTO),
		CONSTRAINT FK_PROFESSOR FOREIGN KEY(PROFESSOR) REFERENCES PROFESSOR(CPF),
		CONSTRAINT FK_PRODUTO FOREIGN KEY(PRODUTO) REFERENCES PRODUTO(CODIGO)

);

CREATE TABLE TURMA(
		
		CODIGO SERIAL PRIMARY KEY,
		N_ALUNOS INT
		
);


CREATE TABLE COMPOE(
	
		ALUNO VARCHAR(11),
		TURMA INT,
		CONSTRAINT PK_COMPOE PRIMARY KEY(ALUNO, TURMA),
		CONSTRAINT FK_ALUNO FOREIGN KEY(ALUNO) REFERENCES ALUNO(CPF),
		CONSTRAINT FK_TURMA FOREIGN KEY(TURMA) REFERENCES TURMA(CODIGO)

);

CREATE TABLE TREINO(
	
		CODIGO_TURMA INT,
		DATA DATE,
		ARTE VARCHAR(30),
		CONSTRAINT PK_TREINO PRIMARY KEY(CODIGO_TURMA, DATA),
		CONSTRAINT FK_TREINO FOREIGN KEY(CODIGO_TURMA) REFERENCES TURMA(CODIGO)
	
);

CREATE TABLE PROPORCIONA(

		TREINO_CODIGO INT,
		TREINO_DATA DATE,
		CONSTRAINT PK_PROPORCIONA PRIMARY KEY(TREINO_CODIGO, TREINO_DATA),
		CONSTRAINT FK_PROPORCIONA FOREIGN KEY(TREINO_CODIGO, TREINO_DATA) REFERENCES TREINO(CODIGO_TURMA, DATA)
	
);